apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-secret
  namespace: flux-system
spec:
  interval: 10m
  path: ./gitops/clusters/homelab/security/cloudflare
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager
  decryption:
    provider: sops
    secretRef:
      name: sops-age