apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepo.yaml
  - minio-root.secret.sops.yaml
  - minio-cnpg-user.secret.sops.yaml
  - helmrelease.yaml
  - ingressroute-console.yaml
  - minio-bootstrap-cnpg-backups.job.yaml
