apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./infra/metallb/kustomization-install.yaml
  - ./infra/metallb/kustomization-config.yaml
  - ./infra/nfs-csi/flux-kustomization.yaml
  - ./infra/longhorn/flux-kustomization.yaml
  - ./infra/cert-manager/flux-kustomization.yaml
  - ./infra/traefik/flux-kustomization.yaml
  - ./infra/traefik-dashboard/flux-kustomization.yaml
  - ./infra/kubernetes-dashboard/flux-kustomization.yaml
  - ./infra/coredns/flux-kustomization.yaml
  - ./infra/pve/flux-kustomization.yaml
  - ./infra/truenas/flux-kustomization.yaml
  - ./infra/omada/flux-kustomization.yaml
  #- ./infra/jetkvm-cloud/flux-kustomization.yaml
  - ./security/cert-manager-issuers/flux-kustomization.yaml
  - ./security/cloudflare/flux-kustomization.yaml
  #- ./security/freeipa/flux-kustomization.yaml
  - ./security/cloudflare-tunnel/flux-kustomization.yaml
  - ./security/authentik/flux-kustomization.yaml
  #- ./security/rbac-oidc/flux-kustomization.yaml
  - ./apps/test-whoami/flux-kustomization.yaml
  - ./apps/homarr/flux-kustomization.yaml
