apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./infra/metallb/kustomization-install.yaml
  - ./infra/metallb/kustomization-config.yaml
  - ./infra/nfs-csi/flux-kustomization.yaml