apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catchall-nasbenito
  namespace: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "1"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - "*.nasbenito.com"
    secretName: wildcard-nasbenito-com-tls
  rules:
  - host: "*.nasbenito.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: default-404
            port:
              name: http      