apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: catchall-local-nasbenito
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`{a:[a-zA-Z0-9-]+}.{b:[a-zA-Z0-9-]+}.nasbenito.com`) && PathPrefix(`/`)
      kind: Rule
      priority: 1
      services:
        - name: default-404
          port: 80
  tls:
    secretName: wildcard-local-nasbenito-com-tls