apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: catchall-local-nasbenito
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`*.local.nasbenito.com`) && PathPrefix(`/`)
      kind: Rule
      priority: 1
      services:
        - name: default-404.traefik.svc.cluster.local
          port: http
  tls:
    secretName: wildcard-local-nasbenito-com-tls
    domains:
      - main: "*.local.nasbenito.com"