apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: catchall-nasbenito
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`*.nasbenito.com`) && PathPrefix(`/`)
      kind: Rule
      priority: 1
      services:
        - name: default-404
          port: http
  tls:
    secretName: wildcard-nasbenito-com-tls
    domains:
      - main: "*.nasbenito.com"