apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - helmrelease-crds.yaml
  - tlsstore-traefik.yaml
  - certificate-wildcard-nasbenito.yaml
  - certificate-wildcard-local-nasbenito.yaml
  - default-404.yaml
  - ingressroute-catchall-nasbenito.yaml
  - ingressroute-catchall-local-nasbenito.yaml