apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: homelab
    credentials-file: /etc/cloudflared/creds/credentials.json

    ingress:
      # WHOAMI (public)
      - hostname: whoami.nasbenito.com
        service: https://traefik.traefik.svc.cluster.local:443
        originRequest:
          originServerName: whoami.nasbenito.com
          noTLSVerify: false

      # AUTHENTIK (public)
      - hostname: auth.nasbenito.com
        service: https://traefik.traefik.svc.cluster.local:443
        originRequest:
          originServerName: auth.nasbenito.com
          noTLSVerify: false

      # Default catch-all rule to return 404 for undefined hosts
      - hostname: "*.nasbenito.com"
        service: https://192.168.110.242:443
        originRequest:
          noTLSVerify: false

      - service: http_status:404