apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nfs-csi-install
  namespace: flux-system
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - storageclass.yaml
  - test-pvc-pod.yaml