apiVersion: v1
kind: Secret
metadata:
    name: authentik-values
    namespace: authentik
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:JWPhyAzQ/mXoqnKZOHtN4pHqG73Qiygfk+KqV2hrC/tlDlkR8N7lzt5pR4yfrC/SZMGZPDw45hhBuYPLs/mLpXmElP7IkqvuYgCIpaMjiiLpkez82Mi+IrjAQHwykbworKWqjcqywkXUH2zAvPJJKzn2E360q+vHskofYv8FN0dIcJy9PIUJPjqvFAio1cJv744A/rgHzWhdZcIeqSz976PaqbebpwyKObOUOz22Cj7s6s1pPcoeN8B3G8rVHQ/lgYF5nAdEV5IJh7+yTv2KTsFAxaLD3QDy1PsthuJbbXc+bNnObLhg/hHJouXICHLu4mJo9kypKW+mUWCBl3jJg8NKwYaGMQWLWcoB7k7sHejSSenFGNdbY3jzJ9R8Ti1rFbM81bJ+Dwnaztq3OtiLYrD2dpiHX0tgiUnmXiblC3H/YwgEnt/j7Ip/N9Mj3fDs9qz82G+2Pi3DOGsQ4bYuFd779MwJOPeEQBtbucTydM9BbLkge/pQ6XQyu9kEsqp0E9wkM6x2z3GZUt+xeSiGOb5sJLT3C/XYyzj3oCceanlcaB2M/NfHsA66tTYf9kY3KFugMK1tEWcBT4v2AJKHJbkIUqN0IewpG2VnvHQnzfnh2OK1Et9q0f6upCLfm9FyFL5+XQaOtVla/mDc0R/ZDW18+dh/GvNEgqYEwjiGeNaOHYGyJyTWplWKNG/4AjTouLtOIOYtg9Uyw8ol8VzobWaCEm0cKGrXop+QctDHz3yocQbunUEqqlsV5afRLNJOZiFtmBs8IzXIiy1LS7RiQ24pkuc3+AobTg39qD46h/CkdW1vsXvMEfDBSUHpe9fHMtK3FIwDwOZRgFVZ5ESxkaRByg==,iv:qJ/vz8HGomMAoHMWXYJdP35Ah/uAq2eqKdDCQi6rlO4=,tag:XgpmKb7WyfE9Lxg6oWoP4g==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRjEwMG9zT1JNMTJKL3NZ
            cENKNURxVFBFVXkvcVpXZHNlUDcyeGNRRmtBCnp3c2loMUtKa3RPdmh4TEd2dGE0
            WkZMOCtDZlk5R2hXY1RZeHJNb3dCaDgKLS0tIDdyeUN5MUE3YndCNG9BdmVra1NB
            cHFPYnVBb3RuQ1IvbFVJY011RDB3TUkK0oER5Dcujfl55hrtZwFQ3XIcRRc7CMOl
            0XKkSqwcv7Ibww6kijsJss6pruNx7tKgmpT4e+jSqGvPsjBpXjHv4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T15:27:32Z"
    mac: ENC[AES256_GCM,data:aJ96y8IoY4z1VhokJCDzzV6NE6NPMoO2746UL0okoIC1dCwtSlKQbFg+uoChEBuyOAPf3u3LoHGogdXNT5iUrogqdX8ZYCZ5O52PNvVJwY0SCOEzKhRKBUOGDWy6cc/AIu5fgJvFIi6N0r3Wu985OIykGOppMdo0ZJ/xgsXSiPA=,iv:Jvlik+cZ3PKTZ3Xa1e9z0fAibUbwaim395QZAqU6ZvU=,tag:QH1d+gv8s1fsZCmAlYn+9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
