apiVersion: v1
kind: Secret
metadata:
    name: authentik-values
    namespace: authentik
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:uRBSG1v4sSo+uGs67tVClAuikuvIVOyQ9w9/VnKv1C20FI17eO8O4wr/deQErstUGnOuNc4/n8K5luWKGUaGCHvOeSwcI/EzP3ppYiZ59q+nJ8FQnnOl4891awVQhTWnJFsIvFiGF6RNaVJMROt3timPMhPkJap9a7zthTfcqg33MOXrpEfQECX6GaZiq5YOiJuIv9DuBe7U1AgbJvOigJIEbLm78gRusvTXePIYI9jefRYxRiV64RzdgSa9+KvRJXn9KMrd/yPVRc2LfvOxACQqrYcek3FwZUAMhPnGdqzgjcO/nInN8wX5YFpwTTvVTN0lUGIy1G2mx5tYdYnSU6NoEmiRwgTJlcUEYQyryEJh+pEdQYhYMCRRNXJbrMQlKjPVZCUB1RlqmUQSqTuqVDdFotXOMrAD/sBIK2e0ShoDbjqYSy1DsYTDiLxj7OYsye6mVXDUqbr/Wi0HxSi6UHB/U6bxLUKflDZSh+9Ce78EE3MeHSxM0qM39S3hBCtat73aMPKL9x7logg8YRdWatha5kr05ckMMia23Kkb4yvgRr3mSKzq+vwweZW+k4leW/k2Fzf6c0I10VTJ8PqoW3iOR23sEYtKLb7Q3SEUCPpC5SdrC12kN7WJ9gFHbkvEH63zW7TCeEsD2WM3cEw34QGWAf25Hox+EKxcV+16ubenA9+nAa9toUeJEJqmx7ngmD4gl08M9mjKacs=,iv:/IWj+gP43AoI2rQVhqJ2IpnBeGbsCfITd+NooDmuDEw=,tag:PY88f9tMvmgi1s7Fn2L4MA==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRjEwMG9zT1JNMTJKL3NZ
            cENKNURxVFBFVXkvcVpXZHNlUDcyeGNRRmtBCnp3c2loMUtKa3RPdmh4TEd2dGE0
            WkZMOCtDZlk5R2hXY1RZeHJNb3dCaDgKLS0tIDdyeUN5MUE3YndCNG9BdmVra1NB
            cHFPYnVBb3RuQ1IvbFVJY011RDB3TUkK0oER5Dcujfl55hrtZwFQ3XIcRRc7CMOl
            0XKkSqwcv7Ibww6kijsJss6pruNx7tKgmpT4e+jSqGvPsjBpXjHv4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T16:41:01Z"
    mac: ENC[AES256_GCM,data:6a0nKrI7XOeKT4gBvUax4Ruay2vdTjjBvP/PsY8FRIApCIPDx/x09IpExcTRqbky0N0TjZeAPkwVzNRz/3mNhYbHTelJD3wV+5mSy9Wq85sOsn/K3bOP/XmDo1g8wjegffB4RNmWqo58GsH7inw5RCLogB9UM9zvmdpQGlvtyNg=,iv:Ai9cSq27cNPHAgpmtmW6qOcNgWEVlVVRvHnmFjfqp0E=,tag:wW+ohFy9Vgv3IO71TDQbmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
