apiVersion: v1
kind: Secret
metadata:
    name: authentik-config
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:+AGvCISHRKMlrhnSzd0q4Mf/SyKnRJ95l/w6LzrBOIRrFryQXh15qhEI1mD9RgJ1IgohCKfi5i1K2nE=,iv:tYgTj7aFwSTt7BkpbTidVPax1umoEzvx4K/B+fS+O4k=,tag:5/Eg4sEUV8iEj5raACALkw==,type:str]
    AUTHENTIK_ERROR_REPORTING__ENABLED: ENC[AES256_GCM,data:QdwmiJQ=,iv:KZkXVvAlhATni97mD9iu14U28I5ylNsiXpZPXVlGdRQ=,tag:N97oAMMUq7FLxbpev/IFNQ==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:aLVfHQw1cboFPTIm8VKdFmGjo7Y=,iv:gG6/FWNBAHl70hvSNA8RBgvAZ/HDAW+CpH5ccaT+VDI=,tag:vmp9eZpDs+WHQh2HS/l47A==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:BVPV2Q==,iv:nlhkSGIiHv35EJ2XEJowwCquUy3fdCCQfxKVNBYwnU8=,tag:35m5AGS6+ESerKAS0/BuUA==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:rUfWQmwg3DF8,iv:+dbvNW9LZrsYwjR1qsLw/mPWFr0OUvi5iQIbwCR8hIE=,tag:hKamMp9vL7p5LvWRmOLsyQ==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:9q33hLffUPR4,iv:3/FeboKm1sepTJIQDjM2bhleWk3IHPRbQE8y9bWc98w=,tag:HmN0gDlD3yzMGQ5s8E/j3w==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:4linIIPKlS1bto/cew8dv1Axypo+bA8MB0dHwcyiwXCzxzcQjW86JNNQsDk=,iv:WATb5d2TSY7V1Qa+w9jzUUL9KzfDsbUUxd+P5692z3o=,tag:BiiAcnGL4rFDdDZNM/t21Q==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMFFrM0FtenFjeG5IVUtu
            bXZOVWtIVXk1S2U3emkrTGp0dzFtUmNZR2hzCmJKak4vaHVhTTIwU2E5Tytzcmwz
            NjJudlkyKytMRTRQNHFzTnRpemhPNDgKLS0tIEdza2JUY1lkaWQ4YktEcm1NaUJt
            TkxOZ0FpbytKZGxoS1l3OUYwZnZKSlUKQy5oziAiXIZvpakGDzUDQwXZETDv/Gc6
            hxspzC7HAi2sOvE4XSDHapb0cKn44YscA37k2IMQRlbnrAdfE61eCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T22:25:02Z"
    mac: ENC[AES256_GCM,data:k2bJP99UTQfIBgrG6vWAVHRuypCCeHmPDLV4peTbBNOLJ6onmAC3RpGXVVdM3QOEI3PdL9P7edCFvWDt2Zp6q1aBHk4r1pbdx0ZwKl5NTIcNDJud4Q095UFvTmmMD/aYeBdJIENrdObsAiQeOGE2ZeCcwCziCf/1PktKYZKdIvM=,iv:Tb/1Hn8tAbU/3On3qPq1Xc9ha7J4fhZqho3u9MSkDoQ=,tag:A/I9GsO9k7lTJszTVTSmnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
