apiVersion: v1
kind: Secret
metadata:
    name: authentik-values
    namespace: authentik
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:c5kDV1EimV30iI5Vf/dMhhYL5oK5aLXtegJl2AsmSZILJQANs+JMKNDao0BMWbqSz0O0TMBeHZ9RoUXcEWErOPgdMCSm4PFAo6NoyKUR0RtyF/OsvYW9alRxbwVUyH5c64VkPM8/F489qRg8JNbTuE/bJg57Uyn6mJlGpG9V+VvrJYAOyXI0FBAwk8PdmHgU8E+35nssXMP0lnKjZu/pw/KpJlIZ4FZEwR/9EMBMUOyewM+EiyWv21tuFFGFKwMQJkURRpQCgwRc3GywRlzBMBxUPjA/npX2d2dcvzmKub2SBt9UO3zuIgzJSfS4j/aWlMowl6PUBDNGCUiRSUmTJmvlm0y3pXPrU6TkQ5GHPCOC/D8A+1zpyLwikXL3LCuYaMhTJFdpxePvaVlFTJrEwO0zqvzQ+wdvwuhl+NRKMkg59jXQAEorTY6i1eIWPPGgJsSh8PhgMSM2tTrEazIJx/M3mrjti9r/TwPZCcnqpjJv65SAQCo7lxkx5YUHSCpxtnAbUJn/CI/V1HM0imtCCid8x5LCGwbJOuWRTbthJDFn+fiv1/9SqNjgoLAle2MCkImYSlTauVAHbu2tvSdVetkqVHuMQUhj8mL+DF1Rvit/nA78N4/AAGcdxqtUfhjAe6dYqJcV9Kifis8iSnkU22ON+B88leLGMtcE6QZExG+6j3DEGxowfDqCxg4Z5sIeXwzYKVWD64ufn5rRIxzmCKVsqaOvR6Vd5ALsEiNXluY8EKv3tUmbWaI+KEtF/s3moIvLHTQqydWBCvloe7SipgqUQhC1djN46Y3wCKv42iiFuejLGM1zjCakMsT0h08TmQEYXDvQ4lA5k5XOnIhpGOYRqvaKge55l/JK8zMyA1ZWz7hktPJ3zUJosqz6LvKIuovsfTy6jK9u9H5TGlg9b7kOUfzmbP8Xx6O4xBFpHLyEipTJQ0w27nL8wZRSEGIcR72VaVD6qeV2l6ECO9IZ6EtlWOdhSeKrKgluxOzIFYV/VwX5lqfpT97viDYZNgy/jWrtr5gVmWjdZNa6AhR4r9q+EURH8Y3AI6KPAg1ExA5+nL1VDrTb9DNjHxyRsaLG+/UwXt2ACwIQciv7rJxNsuiNVtJLsPyPJZdkv6ai9/is6zaOrCEyamNuEyqeRnKzBQLCahSCviwLKb0ky3dNJ1NOxtawGkgpu/nnuznLW/hwq8oVv6NHUZ8onrThiP3LXRVFsjSNWnj3XH7L3EyNXsW7Z7hqvdP/XcKnAn/vflz4D1vIrpAOROw80S1ONVP+chRPoJjzqRWI/eFp9HHLUBYbwLUD3Sd9lITH0QOXB9oc/lHhx1HT/MdvltnzIpocxw22HuD6iiDrHXksiA==,iv:SER/2kMim9H8P3NTiPZu8Pvpea+2pIwli5TA3NwbHe4=,tag:379RHoRcfb1SPlflL4oH0w==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRjEwMG9zT1JNMTJKL3NZ
            cENKNURxVFBFVXkvcVpXZHNlUDcyeGNRRmtBCnp3c2loMUtKa3RPdmh4TEd2dGE0
            WkZMOCtDZlk5R2hXY1RZeHJNb3dCaDgKLS0tIDdyeUN5MUE3YndCNG9BdmVra1NB
            cHFPYnVBb3RuQ1IvbFVJY011RDB3TUkK0oER5Dcujfl55hrtZwFQ3XIcRRc7CMOl
            0XKkSqwcv7Ibww6kijsJss6pruNx7tKgmpT4e+jSqGvPsjBpXjHv4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T16:44:37Z"
    mac: ENC[AES256_GCM,data:H+nG5IqSEN95qWEsZKWRHqMMAOY1d06QJWwX0kDWlt85IvNglbyRImgFfJwQZF5WjfYD63xBn5+baxoCIHPTkVc4ywbWIg5k+p5PH9A0UFKyEnb6nLVencEu4MRMtznyqDQ5ilskjhx9SbXC0WJTYvrTVD9l4rUYPxn5Y4Fhu8Q=,iv:IWF4HtcsbJmYOMHDxmTvLgJ4s0Slxf2+G44HEXjKxm8=,tag:Ee5C601x7DlqYhlh3VfxBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
