apiVersion: v1
kind: Secret
metadata:
    name: authentik-values
    namespace: authentik
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:eAGE9MJAJB3TiS7rvUBxKIMiRayORY06A0he5yoLLxGGsNQO9TTVKuu2s/GieAF3n6tZWxz3LgoCINJhuKrSMTS64sxaswXargvCa6vJXctcN76baUzvqrL/w2eCMCLYaZnbKHLslGvGIoFJ6VWyDKVqjQ92rnJpG/EmKSLKtFbbisPlNuSCUzrTPQ7b75lMf48COxx5BMyb9y83fI+fJlRf1sNxnhh2NISykvK8/SQbj+BMrAT6KoHDWFl9p+tunpBjIOF1x2UtnQaK79xNz+E8nqt6jPejQ5H1FcZivM/iqIlwF4PBCBD9hU4CRcR29XnSaj6Na1WsY15UvNI+Do7jpkLme14IoLf9K0fcZZtifjTc2P1WA0vcns0rlj39h4UIxr+fu6cPLwwkCJ5VUwVMAFEdFPGQXIbTIzzaGOi3DJpNQpfNSUV9jvDpVX7KIwSPth1vsatUQQAZFiFrLKNYMMZflJqlKyWDjz+wAIpVlPFPZkXEnDnNYjYlCrTuqxrLnSQ+jEKVu8nt1fHA6GMbfF8Yf0BIrZzcgkWaOcXLU+0fLIkurdEWMTCcxQYa0pfZCVejSHDTCmvEhRp1BEJtnCtgNvmCe3SLtHxglvC/nDyLs8v9q8hB0jATFCyrYGtqyVlOMIAhSQGV/9rfm8Gjhuo3ggk/mFusM5EhUq/y4Yv/LeJAa4UgI7mNqPR6bEmRhje1P/4jFuO9E2FIam1JyBkA/tXUwn+z0JrQ34Wfy1BGIdm5dBQxgO4ar/sWyQByrahTVswv3jwmiCnrG3f3xJvyJykJoUekODlx3XUtxEZI481QV4HearayG7j9lsP1PLHIoaExcDbJQ9/JeuHAPzB6Sbl5D/17XVLgMhH7rQbHB9hmPuscs/KQyl/Wf27W39ZrMRx1hkW9IIOor6mS9zAqInoVqKtuabKGIGzdm8zg3iMrb2rPhvpWLs0l/5i8KJOAi/HeThyJed42Q7p9NypdhwvdbBD6cnoBJ1DTOrgKKz2nnaQlgZGn0Pjpt7Bwf3/nWQF3WutxXVpKT17J8eyIFuGdaErXnZ6KDiffgW9Vmq66c0iYO4WQO3hsQmqmYSzH09UxoaSRNj3pF7KMWvsPxQch8uqAgOCT/5i5+dGBSbzjGL6jyqpMSEf1FuxuOTrAYx7pF9z+/zEdj//opv5wLWVfG5Q0Mlwjw5LymWc/Uo7f7Hfu4Z09DOClF+01zVx5yu2V/tbwnIQO6ebQfgpUidM283wEQTW6b21Cu7yOVJgmWVx40FJV6DnVS+7YUl1e9zS3fl04pAaaN2qFMmAKccYF2fVmuTFyO0yIybBJ4eU/r3Hx9NE34fg6ZZ3TTEBhWKLapIZY6Mvh0zKEV+xLaQPxydsbVYTJtA4SgFAabO9/mB6MIFt/Kuey+GdSWs3pHt2sJoiLQYQmph9OiQY4xYqADuleUQjMwtAYtOAzq2ZflLe2osJjH5bpIM9NjFE=,iv:axpg+whlSJdUui1LEhe6Es3fjyXLGmKIt0SeA/zk2ZI=,tag:YBUOMbgfrQ+xM+05feP8rw==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRjEwMG9zT1JNMTJKL3NZ
            cENKNURxVFBFVXkvcVpXZHNlUDcyeGNRRmtBCnp3c2loMUtKa3RPdmh4TEd2dGE0
            WkZMOCtDZlk5R2hXY1RZeHJNb3dCaDgKLS0tIDdyeUN5MUE3YndCNG9BdmVra1NB
            cHFPYnVBb3RuQ1IvbFVJY011RDB3TUkK0oER5Dcujfl55hrtZwFQ3XIcRRc7CMOl
            0XKkSqwcv7Ibww6kijsJss6pruNx7tKgmpT4e+jSqGvPsjBpXjHv4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:23:39Z"
    mac: ENC[AES256_GCM,data:Ctgv3mqGhmJ99JodhQc/WG3pFp50MLncvcpRKgw2DM1LK5C+4HsbIeSqPZhPLN2DceUirIAG+DAlqc+dpnvB1Pu7g8fUbhQ6twKIHrarYLfTtyC/hzGKh6i3g0eNiTHpQlZp6UfSR0aeljjO75kGAgpa4dE6y4KsKAmrLsZ/b88=,iv:57VG2rCUF2Y0oa4dTazE7pHbIbEu+fcZ3hvCgDAwF8U=,tag:vU4v8iDBkOdBstZlb2ACqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
