apiVersion: v1
kind: Secret
metadata:
    name: authentik-values
    namespace: authentik
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:4o0zpmykWqaakk3zAwMVS4CQY14dcbLMJtgIXL+Bm8uujkhAgK0cZc/qvt2KIbf0DYyPLT4+wTrxrGBtnxxxOhI/P4EgVj4lMDhik+arvl/qwkoVYmSfe5fmMaDvkas62P+o7VM12weCaSGNJMsLQS7qIHAKQaBXkGckHfonSwkLOHG3afkR7xkcPsVythNVRLIUqPjHKk19B3pU3G8tpNoC4z/5n+e9QxJFN8tyx1+UuwdBsWW/bRr5yKwUdda0+BwKFVaR7/cnPfUol58tpzzqg9GvlbwX8UVP8OVSuqekXjcZ15M0pQX2bbYvtAZ+QFm8shqVQZdv9m+AqR9n5zlOC/xqfiRqkfXoYVT44s2xq8/PvkGSCKtjGO8LNg2Dv5kJLvP7lKHghPT8NLniG500u5Yr8mnbEcUELl0Kyi//uozPyVr2YBwkyzRynCDLIZ5dxqjuSzwP4PRkxCPSJQANpYbY85rnXiTbFChPvv5w1epDfQNAYwQXD9rkKcu+MlCqAsifH8A+suKiDNO8jqrHf8IalQ46zNc0wM18+mrLUwPUaw7nZIK69Kp/8IvTLGjUzOLqUVwnN64PfeySGbNmNXwhm2Z4TuGxeb/183rA11WqJS9BeMOGmoX4qWq/dSzYEwaLLyMlNFpsPsBhH4geEEIVai9jXcerDy0qcnLzmqqayYR3cbC+46jjvrRKp7S8GmYlBt0j38V7T0YTmQmaQTkIauuvHm+eYFmhlJ08VnUnuwuHVyXBHBV6SLQvp+XIqTw/GjjDsFfas1HaXEMWkaIWadVaaDqklNADcSYcQ1qaTXjlIJG4eVKPaSDd12MAxjYf9a6SPAbvTWUtkWMMW2f0loB95jEWK50yKu2lomYB3i6OwSCO+ajnKtxKsnaRCDAJzqy0/i0nMwGnFQpnhnfahuebkig0x54lxnuDYZk0ctgaiR98xhQ8Y6YUSHDOdETOlcgdh6HcJw/HgjYs8sCyBiY0/Qz+/YDEg+FxsK2zDFWskqaVveQVeE+25bTZL9T6w5KYcMZlJ2g+Sx2io7WC2Ni/60pGpzUa06kfIUGabsLp28sQ7ao1gAAdpdDKH8yrtJLZhlaxGLo9EpepruC8v4dXbpFQUtMVLWAiwqfjOcWZ4gBhtoWey9gW6SBZ8qTOmiB2ItvShP1O7EYMCXlDU/PdIsId8mlgypR9o9HdDjK7vhaCB3SgNsUVTZad592Ou74d389mYvMYOVXakgWM/gWNK8lD+Uxgy1ctx4IEIhRbm3lsB+oJ2ZxgbyLbWmT5x/wWUZUz3MYMfHw1KSIsRgwjPeOUarzKwHT9o12aoJ1R9q7Qoc9qIKRm2oJoe3lB6NgqRl2XtljvQC3dIPxGPqld3aGOsBsqSy6YDE9jrG+xJ4mKkHQj3ebqN+vnataKfeX1bE4/hunmXL+ekcCoBKqxzfL2SfxHedUL/Us4S0wiGIT/k/YMQaltYNQxEW2/iRhjKFewafa6wW3M5RuJ11UjbET8JyLTZlAVA1SNNFToB6Ff+kCrK4e7QV+7Nl9qFNxTsbJNNMUzPS5Lx2+2QrY7ucDaeVh4fdd1FBLtKfvJqpvK96WZ8/Q=,iv:vmDsgVtDSe8VDmr9GhMh+ILr/VbST1NDJ1jbz0Mea44=,tag:ZW9qdCqYUu223qqPRxSuqA==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRjEwMG9zT1JNMTJKL3NZ
            cENKNURxVFBFVXkvcVpXZHNlUDcyeGNRRmtBCnp3c2loMUtKa3RPdmh4TEd2dGE0
            WkZMOCtDZlk5R2hXY1RZeHJNb3dCaDgKLS0tIDdyeUN5MUE3YndCNG9BdmVra1NB
            cHFPYnVBb3RuQ1IvbFVJY011RDB3TUkK0oER5Dcujfl55hrtZwFQ3XIcRRc7CMOl
            0XKkSqwcv7Ibww6kijsJss6pruNx7tKgmpT4e+jSqGvPsjBpXjHv4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T16:52:18Z"
    mac: ENC[AES256_GCM,data:fisK7s/76SFc0rmLdsgJnqQV3UG5r5nlutATeqALYew5ykd4hQ4FCI3C7DNe0tfgyqr2OixmAwLfRdYyeRSupC0zbAGsURUgBwDCuvJEA87wJttn5ApBd4D7LiTlRX7qMta72F4vc1aAJqBULWFl/bes0T68L9P0Rl4fwMcvmxk=,iv:8VF2w6fm3n66jQNBvdvQh2z/fTZKwZnw7970BT6wsWo=,tag:007qSypIfT5qOjQu6USOWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
