apiVersion: v1
kind: Secret
metadata:
    name: authentik-values
    namespace: authentik
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:dTVSqRg/A9odxjemVkIGJ6vLCWGpnjz6BGD6XC99mbrgfWYWQWP/0zeTv3LcZtFsZ6V9Zg///Z00gnDEvEFF1s5NFYRSrTM9sUvAVJiHX0rnQYlzRDLqAnBPLrbBp+I88bIo14rPA2KX9X/ug2gDMm+XKePGTJaV7tjyIhyr/0e941Yl0MRUyeWoNctP8maMd1ROVR1HfQueXQdQKROQFBiG9jPndAHU0O9upACAf1q6jOigpQgH0NPhPw5+Maw+l5ks5O3ohdT1XvUkmwcXY0d6EMBAuRK7lZkOt3YOHm9KW+9hiPtSIxSyhf71jOTcRmL7LWb2rBrSUpogdVmhkZNomqxvLv72e3KPmqu1hhQkiT4OlDMSoWnMhogatbcYnlaEuAi4eYSC1mCm1KLIv8KhMZnSfUMSaNxy8Wngf8KboT5MEyzxCqKFJFrBJOJ0JOe7EyXehEe+myUAK5sn5mu4/+Sn+V9TloY3OoAwbJse1QFcrPKERNeiyjQVz4oLN+fjmIMyGuoF6QGEBq+Y+ERIxCdt+osMMub+i1I291JXhzyK7DQ7MJabb6a7sziVXipU6cOcYAIulZhO3GwlfrqdC68xgAg6lOEAq56VC1WUQDPOSKXvjIMFQIi+yym+o172onThQ0oAhROtLJpIXnQafZ9hxAxX8NuyvjOPHGuXN1zhGT+3hivNdtMhlfvcDbsrMchdB+fI1Zq5pDyemKzw29uEBXcTZKdEOxcA+lQy425GqgFvSxQvZYqna1Dzt5/peLiG3bxM3oY1/IqPe2YqZ1T1XZuvdy9NoQrdtmv9N58cqju+uY6EYFUeHvekXTI/KWX3Iw+35uKF85EeSbAcrvsiTRqVdX4Ysi2LFhL0zmAqPRQcXifoMAGKgyJn+0rskiu7ynebqGILtW6/BkUVqeGaHvCT0uYJvtzSZI1yCniPD3ZxIIu3LE5J5OiQi9TpJIzWwM5Fjeg5fN2sh+/yjdTQt2SL3JzHGM7nT4GaHSNrKnAg47GDemSc7hODfQBfqs9OK86717aA9d5RUo/SCkGal0ywT4DiqNJ8xKo4oTSnBfS4q1T3ZfLEnLkurj9HB1icVafZdv1zUYWKxpO99/eTPlcnXm4Nvb7PhsW08722GHZAPfkV0+RRXFdS+0/8tVnc7zVr+xIueaukRMIUcqyk0DjXpOXhFeQnoscMBl/XDoemRK2hhJGPjMCmQD6r1il5LfzItFl0Nb51T3q+2yM9O+rfLDoXpOYd9NZo+m0K6piPD7GRvUB8fxYknYooMVj3Ir0aBSfZNolWQGqRosQDiy6DPopNWUavbhPHzsS72T3KHvffI+5NXOS1AGHZrs9C64fXlJwP/NxdttPJNbhC95jnHukFk1v/ZOIdTCAQDBhxcUKu3DLfMZK5Juo5PF4XdNBuwvV4FcCdzYUU/V2HPnFz2PzPuZBf+O+QiedM/Gn2A277dOqJpw3LrjbBWQcvXoWo9PjLF5hHqwxLaAuM4sSjnPivT9SHj/JY5eFAdq19ldZumWaNhD30XPU=,iv:pQIZgOUkwN5O6zwHtjeQQYihxbqVM1LTHusBOrWP5DU=,tag:RGe9RIHWbtPwXM934ClWUw==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRjEwMG9zT1JNMTJKL3NZ
            cENKNURxVFBFVXkvcVpXZHNlUDcyeGNRRmtBCnp3c2loMUtKa3RPdmh4TEd2dGE0
            WkZMOCtDZlk5R2hXY1RZeHJNb3dCaDgKLS0tIDdyeUN5MUE3YndCNG9BdmVra1NB
            cHFPYnVBb3RuQ1IvbFVJY011RDB3TUkK0oER5Dcujfl55hrtZwFQ3XIcRRc7CMOl
            0XKkSqwcv7Ibww6kijsJss6pruNx7tKgmpT4e+jSqGvPsjBpXjHv4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:03:25Z"
    mac: ENC[AES256_GCM,data:d6p9ihVNxp4+9gWnsM0S+kdQYomDJZoKh3VtnfsnQ7ocC0mN4m+7BuQTo2M7MEzD2jAOkgPh99xoFdjqcME12wNxrKBRXEcs6q1TPtD/34zfuMrtJ4e9IMRv7ZBy8VVLo+8x5DJ3BR8Tex8+6x0EhG1leTndcESl9mWvdpeZgsE=,iv:LhTDBqnoyfT4QSgbBzMcJrtNbHOIEVR4uh0auYaTiUU=,tag:TlMd82JB1sGNlQRIRHwDEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
