apiVersion: v1
kind: Secret
metadata:
    name: authentik-values
    namespace: authentik
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:20Q1LAqEfihXNS2/DYtg3s1ghNNuiyyg8ZY/OpxsezNOnzqwdzmi90UoB3t0sGeIBR1rmI6vv1ghSRBbQqy74JLtfu/npf4LQunCJklsttUZITOQbdY8CVeyDMWw4Twy1Cy1DcJifRSLvn90oGaE3RB0nengBh9UCFIyftZPP/uJ4KUxTAUZyFKhgGsiAJWQvgq8RPaVBZclHBtJDHn6QYTBDE/+4AHmOW1we/HlSjrgq4Qc+oXSK93rRBj3+4ITvuCBNyBpwkrYvfwySLXy6rSeqEzwrTAIKG3A9Wql2wE3fVOcT80yw1DMp3ziC3Fb9xbJY2CTVZuXNZdaFohhN904p2XupMlZBK49Q8axrYlogjf1cfJ7jmCiILHN/n7EwuQ0xuyB7yTmaBI4aO4637X1f3NS4wW5ohW8fiiBEZbK7U3mi0AGXDwfge3/IhvMaFg+imIP2CcX/DGTixurZAgw721z66adBj6MnEVTU6vGe/yDgRxq84QH+LYnmfYDvI67/iN/WG7igZZDiR2XWK2if6wHvoy0LSMZEUXWOFvsScU795M/mbDoWSCfNW7Jyabmc33G0YdLcU/H0+BXh58WgMe81J0PL3hNzAb1cHt5YHpBiJYowLS0QtoiHXMdure6BgcrAN9la/PXxvr3ahX4f4QRvNTAdcNZFS3zTd9uLwalcGj6dkBACUhBkAtlVCgWvtXFk0D/4KE1TIs9Q0uTS1KF3NdEnHJgJw9zHUzGYPjXaOsMsrhWbsD7Xb2G+HUbxU7VVw5pEVx8CCjSfOgfFw7GcuzTR8WlppPTTQMpEN01sLR6xwOEV11heqXBzJ+Oo2IK7jm394N73A0dsYu7+cA/9ckute9RBj+FJVf5UK3oJnPP4sAKdSatjRdF8yvZU1RVHYazFHxBldJBnvXJRz8J7mHDfx6MWiLE3jcdYNQe7Libk6QTKm8dUDeM8zDPN5sW99PlMD0Z,iv:fVtxdm28s2JmR655xG5WwDE5Qo50EviyAlGC36DOAUs=,tag:uwbaCnW3FgcoK2zrySx5iQ==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdllJdUt1TVZ3YVU5ZTRi
            Ky9ZemExR1NGbjlYa2s2d1QyVVlRVVlvaGc4CnRnQkQ2eU5BbUIvSEROQWtaVlRK
            VVpSWkFQN2h4VmdQM2FFRU82RkUvWWsKLS0tIDNyNGE1cStHcm1OZWFhMGdxcWcx
            UXhyVmtWQUVKLzNmVkd0VVlPeStDd00KZIsVxfjHcwbDN5XEyMzlMkfRbnUQsfyU
            Fe00kRK+0A0IGawe2CQX4Kyexbdbvhp+YGmXab4BQfRYwyfVrAAEmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T22:25:13Z"
    mac: ENC[AES256_GCM,data:4JsbfJMM3EUqrCa+0qYrYZIPKP1peAI1xRxC89bZwogxytjX/e/FMt8/mUlVx0W70wAHDvW/Sc9L/8xafJjgASUOcpKtZ/SbntCYMjwy8p7T8uMITJ6gVMj1RN16un5FEimlohQ9pF514ewGB/uzGHYIyKNO+7R57WdiuOdwgCs=,iv:aODriYHngUYj47QfiKw+QugsalI4Aq4tj4G1lhSIKUg=,tag:fpa6gWg9lzJ7wcTSdYyDgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
