apiVersion: v1
kind: Secret
metadata:
    name: authentik-values
    namespace: authentik
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:6BqpmHqbymGFaj5yAOsdc1Mgr0l/pfEIOXR5TbtbBZEjp+cX+JliQepbSEmItVCJieAco8BTrRCZwm124cnAkYN9b1IRo37Pco3SOboD1jaOnaIbbGcIeMKJC7tbpwPQmAvNGg4iXgu7lIREblmjtTd8JWdFafm1HjUrZHyhQKL+N2uo9QbzI2sDYlwg3gNA9djQAbEIBbsRjoaP4Wdp/nUQ+X2qjVyKebVS9MkkQuJPqwvK5jZnGdc3SszkJJu9a1kT6+PlQTGdjDPM06RK9Ed9sTulJ65T1jpYaizQXIcDLRZZblekmvE2RJXb2SPzkWNcoypERZO/nuzkKSFB4y/croyJryyud8xx7oMlyDUc0FvHMz9BbeNzcVbnvYgtEq5MEheluLUP9FgRrfcmutqgpLKwDzWUXinotcw2iQPouDer34S932SbeyLkfot2eAryHEmYofxRux/BcEpHU3IZmXcUDe4wv/qGaGo1L4HRVChu32ScY7bRJ5eaKHeaq+xVQCccBukASGotAGSkNKkZy/5SomZz9VQard3XHqza4QLZ3hP6WlaIWS+uNJP7ycDdgdO8VgEHFXtG8RSUFeIHBZA2zRFQR8a9t4hoKE6T5ZOb9LEei/maoVcaKUNuvKHegecf9BtVEizta0A3LrlQoqIS171GPhvEcAKpc8NshQzIbfUbEx7n2uzqfj5Atb+d7zrcI0yK3F10ZZAzBOUND6NTPZuNm5fIppge1dF4GJr+QA/Tjk8rOvO9m4ZnfMjQRQDoCaMHZBdWciswjMlSy6SDEPbNkqP0f2VIQFC41mqiOlpVHBImil0bpcPZv1DHB976vZPpeBtY65LJ8BnxgCiB/YxddqAK6QvXmbH943Ud9EWpp8T0g/e5/MLB0S1UmUI2HAfEtLnOrm7APgBaa8ovtUbngy5KDMGeokBF8nIdD1P7QgNtrH6Eb14i0bQoiaMjmbE3WZrOKerksweGE0sOo2W3gMhnGPDR+oE65Uy80Z93rgnOMAYfKvOwlhiMd+8K81qWw+YtoUX4WP8kAYlSYiOvFV/w3A6QIr3VCAZFXW/FpdwjgJjgrLj8ih3x8NRtRFDeYkCwx7rIM6R/0v1kdDdyKgsu0Y4=,iv:pOiCQ/lKZF0+WLB317cetsjSrtVyMrE2tFSaVMUMDbw=,tag:HOO3uBLBGCBHu9QAw+PeHg==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRjEwMG9zT1JNMTJKL3NZ
            cENKNURxVFBFVXkvcVpXZHNlUDcyeGNRRmtBCnp3c2loMUtKa3RPdmh4TEd2dGE0
            WkZMOCtDZlk5R2hXY1RZeHJNb3dCaDgKLS0tIDdyeUN5MUE3YndCNG9BdmVra1NB
            cHFPYnVBb3RuQ1IvbFVJY011RDB3TUkK0oER5Dcujfl55hrtZwFQ3XIcRRc7CMOl
            0XKkSqwcv7Ibww6kijsJss6pruNx7tKgmpT4e+jSqGvPsjBpXjHv4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T16:12:33Z"
    mac: ENC[AES256_GCM,data:g1drDwllmVwodQCnGDbTIAcZ6+OofuR5461BmXx6k8AoFi76bZoAFgGM1gf7iWcn+qTM1s6w/QmJOLaYG5wGTsSWQ2mdrXICbi723Q4V5qCh+j+V6s2lUfRVti2t7PvzuFOMmFjUqLLaFVGtwGmsnG9lTffWAdzkHjhz6GUosIA=,iv:MEayuLMxwjD62v92/86freDmAwe0N5gfa9zztzfLu3U=,tag:9babXJfXBq75k9b2+OyDiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
