apiVersion: v1
kind: Secret
metadata:
    name: authentik-values
    namespace: authentik
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:CFU2mMxZmHEOTeuwqWrs55QtSkSFUS2jwr76+nKSgKbFnkrzL0TiEdHijksk0r3dDH4hNsgSfSxU26wnt0SGI22AUwzL+xKyUSRuJXqpV7jTNHWBO9LfIrlPHTqftxwOnJ8Q6TBC7sBrvwRmqJ6u27rCxzp5mo4gsqC0cXlj71umToHq3yHNSKQLmOOclrT0yVnzy0uQ3aXoFHECIYyrwUk7PJqKz5GFb3PmB6SBsCORB/Stvzt4g5u9wdYmV4b+T+GRql/Oyzti/G46KeP3D1NUoLVZYetwZrebjuaRhKKLhzhsrggOFMqgsOoDwXVNuIZgq0auBxboR4xAgeNYkfSpTsNe8VsfWzOMbLEYSuBwTll/75E/lhCAOau5zi7mi6GL50ExACjr4rwplBNm70XTatnMYnKYJi1A6h6oQsOrAJ/CUYW/He4tfnDQPgywAeN/e1QlcDiJB6F8iaDOhw0Bt9nCGlza0KObLHYhR8ccjqhrM6zaSrG4hLRdTMjp0Uwe6Jfup76iPMfguWYIk0g+dyORrnN0K2OJwm/KFgi9nFaGCQzDYot3dfPN0XcFXCoY9Hugmby4vBIJTPQV0tWcqmTCGnt7qLHPF5DTeuHoRBhjqb1o0pJL7XJ57LaqJJ1p6YU+qyykEqgY/o8CnpY8OloxqasIVhZgkYzALTIkGntiaFXHAEiqaQ982fLIINSAA9qMJ1fE+laas1kwI7indRsciOmH9x9kMBjUO7mFrjnJQHcThn8tfoOgJnNE7wusZp8tlLEIllfhJwo9YH3XkMn/eU4S9eIbuygboUltFLu2s+aRzvQcOoLuiiTjoBeP0HSHwKZIfIENOWjYKByM13SldRs8Rm2WgSoRkXwKFeCO4XD+O2fpFhagUAxN31BcQWt49kGN8+96+YbclgnIli0EK9+lkvvNc39yoqXn2Ze5z8XIYLMqPyF8nLmyajbKInsdn/RFrurirZItnkW39fyhJDGXhiUbErbxiG97Q/gzmKV5CWV56QscDk0PbYujsn7Lk3xsjrdmWNC6gWujsaNCXSsBz5N1MqddK7SFVUABd+eIJkn1MwobMlHPo6wd9Oj2aaEGyZwifjYlj2AnsfofXVk=,iv:Ygl8ek9Q+CDh0Q9paxOWydMeoAs5+prec+DD60bs7M0=,tag:2J8BhfmTu5ymOHycjY7SKQ==,type:str]
sops:
    age:
        - recipient: age1cn34m2qxnzsjrcj3q5rl7htwqeld77fmrl002rxajk4zd2fvnssq6l0vj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRjEwMG9zT1JNMTJKL3NZ
            cENKNURxVFBFVXkvcVpXZHNlUDcyeGNRRmtBCnp3c2loMUtKa3RPdmh4TEd2dGE0
            WkZMOCtDZlk5R2hXY1RZeHJNb3dCaDgKLS0tIDdyeUN5MUE3YndCNG9BdmVra1NB
            cHFPYnVBb3RuQ1IvbFVJY011RDB3TUkK0oER5Dcujfl55hrtZwFQ3XIcRRc7CMOl
            0XKkSqwcv7Ibww6kijsJss6pruNx7tKgmpT4e+jSqGvPsjBpXjHv4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T16:27:59Z"
    mac: ENC[AES256_GCM,data:b1ybM1V8pJmJnptJpRQtV3b+t08GS/LgBHTrYK4997RU8SkMxZOUA/IVeGz9SN5h9xkcEkWdRGOFRxB/F+oVW8eLsaxRL+A+LdZ2yoDLruSbXgkn4rLmBbHgDo6Oi011dSNAXr7y14t+8q9CzUbD/oraA0VVEbWxX7gP2hUwTqw=,iv:1fkzpyV8BCV3vma6zhVgvohBr9Depn6ZfDEoWGtp9q0=,tag:gdxQqvIBAPp94VmnuEJFqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
