apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-issuers
  namespace: flux-system
spec:
  interval: 10m
  path: ./gitops/clusters/homelab/security/cert-manager-issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cloudflare-secret