apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - secret.sops.yaml
  - statefulset.yaml
  - service-lb.yaml
  - storageclass-nfs.yaml
  - pvc-backups-nfs.yaml
  - cronjob-backup-daily.yaml