apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp
  namespace: headlamp
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`headlamp.local.nasbenito.com`)
      kind: Rule
      services:
        - name: headlamp
          port: 80

      # OPCIONAL (si tienes forwardAuth de authentik como Middleware CRD)
      # middlewares:
      #   - name: authentik-forwardauth
      #     namespace: authentik

  tls:
    # Cambia esto al secret TLS que tengas en ESTE namespace
    secretName: wildcard-local-nasbenito-com-tls