apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pgadmin.local.nasbenito.com`)
      kind: Rule
      services:
        - name: pgadmin4
          port: 80
      # middlewares:
      #   - name: authentik-forwardauth
      #     namespace: authentik
  tls:
    secretName: wildcard-local-nasbenito-com-tls
