apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepo.yaml
  - pgadmin.secret.sops.yaml
  - helmrelease.yaml
  - ingressroute.yaml
  - pgadmin-db-admin-credentials.secret.sops.yaml

patches:
  - path: pg-main-managed-roles-patch.yaml
    target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: pg-main
      namespace: postgres
