---
# Main tasks for FluxCD installation on Talos Kubernetes cluster

- name: Configure FluxCD
  ansible.builtin.include_tasks: configure-flux.yml
  tags:
    - FluxCD

- name: Configure SOPS for secret management
  ansible.builtin.include_tasks: sops.yml
  tags:
    - sops