apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homarr
  namespace: homarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nasbenito.com`)
      kind: Rule
      services:
        - name: homarr
          port: 7575
  tls:
    secretName: nasbenito-com-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homarr-www
  namespace: homarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.nasbenito.com`)
      kind: Rule
      services:
        - name: homarr
          port: 7575
  tls:
    secretName: wildcard-nasbenito-com-tls