apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cnpg-s3.secret.sops.yaml
  - cnpg-cluster.yaml
  - cnpg-scheduledbackup.yaml
patchesStrategicMerge:
  - reflect-pg-main-app-secret.yaml