apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-whoami
  namespace: flux-system
spec:
  interval: 10m
  path: ./gitops/clusters/homelab/apps/test-whoami
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: traefik
    - name: cert-issuers