name: Deploy remote HomeLab

on:
  push:
    branches:
      - main

jobs:
  connect:
    environment: production
    runs-on: ubuntu-latest
    env:
      tf_working_directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Connect to VPN
        uses: kota65535/github-openvpn-connect-action@v2
        with:
          config_file: .github/workflows/client.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
          client_key: ${{ secrets.OVPN_USER_KEY }}

      - name: Deploy VMs with Terraform
        uses: dflook/terraform-apply@v2
        with:
          path: terraform
          var_file: terraform/values.tfvars
          variables: |
            pm_api_url = "${{ secrets.PM_API_URL }}"
            pm_username = "${{ secrets.PM_USERNAME }}"
            pm_api_token_id = "${{ secrets.PM_API_TOKEN_ID }}"
            pm_api_token_secret = "${{ secrets.PM_API_TOKEN_SECRET }}"
          auto_approve: true

