name: Deploy remote HomeLab

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    environment: production
    runs-on: ubuntu-latest
    env:
      TERRAFORM_DIR: terraform
      ANSIBLE_DIR: ansible
      SCRIPT_DIR: scripts
      GITOPS_DIR: gitops
      KUBECONFIG_PATH: "/tmp/talos-homelab-cluster/rendered/kubeconfig"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Connect to VPN
        uses: kota65535/github-openvpn-connect-action@v2
        with:
          config_file: .github/workflows/client.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
          client_key: ${{ secrets.OVPN_USER_KEY }}

      - name: Deploy VMs with Terraform
        uses: dflook/terraform-apply@v2
        with:
          path: terraform
          var_file: terraform/vm-configs.tfvars
          variables: |
            pm_api_url = "${{ secrets.PM_API_URL }}"
            pm_username = "${{ secrets.PM_USERNAME }}"
            pm_api_token_id = "${{ secrets.PM_API_TOKEN_ID }}"
            pm_api_token_secret = "${{ secrets.PM_API_TOKEN_SECRET }}"
          auto_approve: true

      - name: Get outputs
        uses: dflook/terraform-output@v2
        with:
          path: terraform
          json_output_path: ${{ env.ANSIBLE_DIR }}/terraform-inventory.json
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Setup Homebrew
        shell: bash
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo >> /home/runner/.bashrc
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Setup Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup Talosctl
        shell: bash
        run: |
          curl -sL https://talos.dev/install | sh

      #- name: Setup Kubectl
      #  uses: azure/setup-kubectl@v4
      
      - name: Setup Kubectl
        run: |
          brew install kubectl

      - name: Setup Helm
        uses: azure/setup-helm@v4.3.0

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.yml ${{ env.ANSIBLE_DIR }}/playbooks/layer2-configure.yml
    